### PR TITLE
Update jquery.sliphover.js

### PR DESCRIPTION
**Pull request by shaozujie**
Add one option for fix the direction.

### CODE REVIEW

**Comment by wayou** [comment]
it's better to list the possible value for the new added option `direction` in the code comment

**Comment by shaozujie** [comment]
Thanks for reply.
Now the possible value could be 0/1/2/3 or 'top'/'right'/'bottom'/'left'.

**Comment by wayou** [comment]
if the value's not number https://github.com/wayou/SlipHover/pull/23/files#diff-d60e13701f6a88a6aeb682913c43e2dbL60 this line may throw error.

**Comment by shaozujie** [comment]
Thank you for your advice!
Now added another switch statement to solve that problem !
Appreciating your guidance!

**Pull request closed without merging**
